config/routes.rb
Mappr::Application.routes.draw do

   root 'places#index'
   resources :places

end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
	def index
		# Place.last would give the last row.
		# Place.all would give the tneire database... which may take a while to load
		@place = Place.last
	end

	def new
		# prepopulate
		# @place = Place.last

		# get a new place
		@place = Place.new
	end

	def create
		# Place.create (:title=>'omg',)
		@place = Place.create( place_params )
		redirect_to root_path
	end

	private

	def place_params
		params.require(:place).permit(:title, :address)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mappr</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
	<h2>
	<%= link_to "Mappr", root_path %>
</h2>

	<%= link_to 'New+', new_place_path %>
</hr>
</div>

<%= yield %>

</body>
</html>

app/views/places/index.html.erb
<h1> Latest Place </h1>

<div>
	<% if @place.present? %>

		<!-- put the content of the pages on the page -->
		Title: <%= @place.title %>

		<br/>
		Address:  <%= @place.address %>

<!-- got the following by surfing the web and looking at their page source -->
 <script src="//maps.google.com/maps?file=api&amp;v=2&amp;key=AIzaSyD4iE2xVSpkLLOXoyqT-RuPwURN3ddScAI"
            type="text/javascript"></script>

<script type="text/javascript">
    $(function() {
   
    	$( window).unload(function() {
    		GUnload();
    	});


      if (GBrowserIsCompatible()) {
        var map = new GMap2(document.getElementById("map_canvas"));
        map.setCenter(new GLatLng(37.4419, -122.1419), 13);
 		var point = new GLatLng(37.4419, -122.1419);
        // add a marker to the location given
        map.addOverlay(new GMarker(point));
      }
   });
    </script>
 
 	<div id="map_canvas" style="width: 500px; height: 300px"></div>

	<% else %>
		<h2> Enter a Place, because we don't have any. </h2>
	<% end %>

</div>

app/views/places/new.html.erb
<h1> Enter a place </h1>

<div>
	<%= simple_form_for @place do |f| %>
	<%= f.input :title %>
	<%= f.input :address %>

	<%= submit_tag 'Create' %>
	<% end %>
</div>